### ISSUE TITLE
critical exception, missing file '01_hp/08_animation_02/05_panties_01.png'

### ISSUE THREAD

**Issue by ta12345** [stg-trainer-annon/BT-Silver-Base#8]
critical exception, missing file '01_hp/08_animation_02/05_panties_01.png'

**Comment by stg-annon** [comment]
fixed, thanks!

**Comment by ta12345** [comment]
actually, still an issue! error occurs during second scene of "dance for me"
[code]
I'm sorry, but an uncaught exception occurred.

While loading <'Image' '01_hp/08_animation_02/05_panties_01.png'>:
  File "game/script.rpy", line 14, in script call
    call select_start
  File "game/00_hp_rpy/01_hp.rpy", line 807, in script call
    call c_r_night
  File "game/00_hp_rpy/01_hp.rpy", line 820, in script call
    call event_07
  File "game/00_hp_rpy/01_hp.rpy", line 807, in script call
    call c_r_night
  File "game/00_hp_rpy/01_hp.rpy", line 807, in script call
    call c_r_night
  File "game/00_hp_rpy/01_hp.rpy", line 807, in script call
    call c_r_night
  File "game/00_hp_rpy/01_hp.rpy", line 807, in script call
    call c_r_night
  File "game/00_hp_rpy/01_hp.rpy", line 807, in script call
    call c_r_night
  File "game/00_hp_rpy/01_hp.rpy", line 807, in script call
    call c_r_night
  File "game/00_hp_rpy/01_hp.rpy", line 826, in script call
    call event_12
  File "game/00_hp_rpy/18_events.rpy", line 2180, in script call
    call day_start
  File "game/00_hp_rpy/01_hp.rpy", line 807, in script call
    call c_r_night
  File "game/00_hp_rpy/01_hp.rpy", line 829, in script call
    call event_13
  File "game/00_hp_rpy/18_events.rpy", line 2298, in script call
    call day_start
  File "game/00_hp_rpy/01_hp.rpy", line 807, in script call
    call c_r_night
  File "game/00_hp_rpy/01_hp.rpy", line 807, in script call
    call c_r_night
  File "game/00_hp_rpy/01_hp.rpy", line 807, in script call
    call c_r_night
  File "game/00_hp_rpy/01_hp.rpy", line 832, in script call
    call event_15
  File "game/00_hp_rpy/01_hp.rpy", line 807, in script call
    call c_r_night
  File "game/00_hp_rpy/17_books.rpy", line 190, in script call
    call reading_book_block(1)
  File "game/00_hp_rpy/17_books.rpy", line 661, in script call
    call book_done_b_check_fire
  File "game/00_hp_rpy/01_hp.rpy", line 807, in script call
    call c_r_night
  File "game/00_hp_rpy/17_books.rpy", line 190, in script call
    call reading_book_block(1)
  File "game/00_hp_rpy/17_books.rpy", line 661, in script call
    call book_done_b_check_fire
  File "game/00_hp_rpy/01_hp.rpy", line 807, in script call
    call c_r_night
  File "game/00_hp_rpy/17_books.rpy", line 190, in script call
    call reading_book_block(1)
  File "game/00_hp_rpy/17_books.rpy", line 661, in script call
    call book_done_b_check_fire
  File "game/00_hp_rpy/the_oddities.rpy", line 696, in script call
    call purchase_item(item_id,price4)
  File "game/00_hp_rpy/17_books.rpy", line 190, in script call
    call reading_book_block(1)
  File "game/00_hp_rpy/17_books.rpy", line 661, in script call
    call book_done_b_check_fire
  File "game/00_hp_rpy/01_hp.rpy", line 807, in script call
    call c_r_night
  File "game/00_hp_rpy/01_hp.rpy", line 807, in script call
    call c_r_night
  File "game/00_hp_rpy/34_clothes_store.rpy", line 143, in script call
    call clothes_store_gui
  File "game/00_hp_rpy/17_books.rpy", line 190, in script call
    call reading_book_block(1)
  File "game/00_hp_rpy/17_books.rpy", line 661, in script call
    call book_done_b_check_fire
  File "game/00_hp_rpy/17_books.rpy", line 190, in script call
    call reading_book_block(1)
  File "game/00_hp_rpy/17_books.rpy", line 661, in script call
    call book_done_b_check_fire
  File "game/00_hp_rpy/01_hp.rpy", line 807, in script call
    call c_r_night
  File "game/00_hp_rpy/17_books.rpy", line 190, in script call
    call reading_book_block(1)
  File "game/00_hp_rpy/17_books.rpy", line 661, in script call
    call book_done_b_check_fire
  File "game/00_hp_rpy/01_hp.rpy", line 807, in script call
    call c_r_night
  File "game/00_hp_rpy/01_hp.rpy", line 807, in script call
    call c_r_night
  File "game/00_hp_rpy/01_hp.rpy", line 807, in script call
    call c_r_night
  File "game/00_hp_rpy/17_books.rpy", line 190, in script call
    call reading_book_block(1)
  File "game/00_hp_rpy/17_books.rpy", line 651, in script call
    call check_book(bookID)
  File "game/00_hp_rpy/17_books.rpy", line 622, in script call
    call chapter_check_book(bookID)
  File "game/00_hp_rpy/17_books.rpy", line 595, in script call
    call book_done_b_check_fire
  File "game/00_hp_rpy/01_hp.rpy", line 807, in script call
    call c_r_night
  File "game/00_hp_rpy/17_books.rpy", line 215, in script call
    call reading_book_block(2)
  File "game/00_hp_rpy/17_books.rpy", line 661, in script call
    call book_done_b_check_fire
  File "game/00_hp_rpy/01_hp.rpy", line 807, in script call
    call c_r_night
  File "game/00_hp_rpy/17_books.rpy", line 215, in script call
    call reading_book_block(2)
  File "game/00_hp_rpy/17_books.rpy", line 661, in script call
    call book_done_b_check_fire
  File "game/00_hp_rpy/01_hp.rpy", line 807, in script call
    call c_r_night
  File "game/00_hp_rpy/17_books.rpy", line 415, in script call
    call reading_book_block(9)
  File "game/00_hp_rpy/17_books.rpy", line 661, in script call
    call book_done_b_check_fire
  File "game/00_hp_rpy/01_hp.rpy", line 807, in script call
    call c_r_night
  File "game/00_hp_rpy/17_books.rpy", line 415, in script call
    call reading_book_block(9)
  File "game/00_hp_rpy/17_books.rpy", line 651, in script call
    call check_book(bookID)
  File "game/00_hp_rpy/17_books.rpy", line 626, in script call
    call check_book(bookID)
  File "game/00_hp_rpy/17_books.rpy", line 626, in script call
    call check_book(bookID)
  File "game/00_hp_rpy/17_books.rpy", line 626, in script call
    call check_book(bookID)
  File "game/00_hp_rpy/17_books.rpy", line 626, in script call
    call check_book(bookID)
  File "game/00_hp_rpy/17_books.rpy", line 626, in script call
    call check_book(bookID)
  File "game/00_hp_rpy/17_books.rpy", line 626, in script call
    call check_book(bookID)
  File "game/00_hp_rpy/17_books.rpy", line 626, in script call
    call check_book(bookID)
  File "game/00_hp_rpy/17_books.rpy", line 626, in script call
    call check_book(bookID)
  File "game/00_hp_rpy/17_books.rpy", line 626, in script call
    call check_book(bookID)
  File "game/00_hp_rpy/17_books.rpy", line 626, in script call
    call check_book(bookID)
  File "game/00_hp_rpy/17_books.rpy", line 626, in script call
    call check_book(bookID)
  File "game/00_hp_rpy/17_books.rpy", line 626, in script call
    call check_book(bookID)
  File "game/00_hp_rpy/17_books.rpy", line 626, in script call
    call check_book(bookID)
  File "game/00_hp_rpy/17_books.rpy", line 626, in script call
    call check_book(bookID)
  File "game/00_hp_rpy/17_books.rpy", line 626, in script call
    call check_book(bookID)
  File "game/00_hp_rpy/17_books.rpy", line 626, in script call
    call check_book(bookID)
  File "game/00_hp_rpy/17_books.rpy", line 626, in script call
    call check_book(bookID)
  File "game/00_hp_rpy/17_books.rpy", line 626, in script call
    call check_book(bookID)
  File "game/00_hp_rpy/17_books.rpy", line 622, in script call
    call chapter_check_book(bookID)
  File "game/00_hp_rpy/17_books.rpy", line 595, in script call
    call book_done_b_check_fire
  File "game/00_hp_rpy/17_books.rpy", line 215, in script call
    call reading_book_block(2)
  File "game/00_hp_rpy/17_books.rpy", line 651, in script call
    call check_book(bookID)
  File "game/00_hp_rpy/17_books.rpy", line 626, in script call
    call check_book(bookID)
  File "game/00_hp_rpy/17_books.rpy", line 626, in script call
    call check_book(bookID)
  File "game/00_hp_rpy/17_books.rpy", line 626, in script call
    call check_book(bookID)
  File "game/00_hp_rpy/17_books.rpy", line 626, in script call
    call check_book(bookID)
  File "game/00_hp_rpy/17_books.rpy", line 626, in script call
    call check_book(bookID)
  File "game/00_hp_rpy/17_books.rpy", line 626, in script call
    call check_book(bookID)
  File "game/00_hp_rpy/17_books.rpy", line 626, in script call
    call check_book(bookID)
  File "game/00_hp_rpy/17_books.rpy", line 622, in script call
    call chapter_check_book(bookID)
  File "game/00_hp_rpy/17_books.rpy", line 595, in script call
    call book_done_b_check_fire
  File "game/00_hp_rpy/01_hp.rpy", line 807, in script call
    call c_r_night
  File "game/00_hp_rpy/17_books.rpy", line 243, in script call
    call reading_book_block(3)
  File "game/00_hp_rpy/17_books.rpy", line 651, in script call
    call check_book(bookID)
  File "game/00_hp_rpy/17_books.rpy", line 626, in script call
    call check_book(bookID)
  File "game/00_hp_rpy/17_books.rpy", line 626, in script call
    call check_book(bookID)
  File "game/00_hp_rpy/17_books.rpy", line 626, in script call
    call check_book(bookID)
  File "game/00_hp_rpy/17_books.rpy", line 626, in script call
    call check_book(bookID)
  File "game/00_hp_rpy/17_books.rpy", line 626, in script call
    call check_book(bookID)
  File "game/00_hp_rpy/17_books.rpy", line 626, in script call
    call check_book(bookID)
  File "game/00_hp_rpy/17_books.rpy", line 626, in script call
    call check_book(bookID)
  File "game/00_hp_rpy/17_books.rpy", line 626, in script call
    call check_book(bookID)
  File "game/00_hp_rpy/17_books.rpy", line 626, in script call
    call check_book(bookID)
  File "game/00_hp_rpy/17_books.rpy", line 622, in script call
    call chapter_check_book(bookID)
  File "game/00_hp_rpy/17_books.rpy", line 595, in script call
    call book_done_b_check_fire
  File "game/00_hp_rpy/17_books.rpy", line 271, in script call
    call reading_book_block(4)
  File "game/00_hp_rpy/17_books.rpy", line 651, in script call
    call check_book(bookID)
  File "game/00_hp_rpy/17_books.rpy", line 626, in script call
    call check_book(bookID)
  File "game/00_hp_rpy/17_books.rpy", line 626, in script call
    call check_book(bookID)
  File "game/00_hp_rpy/17_books.rpy", line 626, in script call
    call check_book(bookID)
  File "game/00_hp_rpy/17_books.rpy", line 626, in script call
    call check_book(bookID)
  File "game/00_hp_rpy/17_books.rpy", line 626, in script call
    call check_book(bookID)
  File "game/00_hp_rpy/17_books.rpy", line 626, in script call
    call check_book(bookID)
  File "game/00_hp_rpy/17_books.rpy", line 626, in script call
    call check_book(bookID)
  File "game/00_hp_rpy/17_books.rpy", line 626, in script call
    call check_book(bookID)
  File "game/00_hp_rpy/17_books.rpy", line 626, in script call
    call check_book(bookID)
  File "game/00_hp_rpy/17_books.rpy", line 622, in script call
    call chapter_check_book(bookID)
  File "game/00_hp_rpy/17_books.rpy", line 595, in script call
    call book_done_b_check_fire
  File "game/00_hp_rpy/01_hp.rpy", line 807, in script call
    call c_r_night
  File "game/00_hp_rpy/01_hp.rpy", line 807, in script call
    call c_r_night
  File "game/00_hp_rpy/01_hp.rpy", line 807, in script call
    call c_r_night
  File "game/00_hp_rpy/34_clothes_store.rpy", line 143, in script call
    call clothes_store_gui
  File "game/00_hp_rpy/01_hp.rpy", line 807, in script call
    call c_r_night
  File "game/00_hp_rpy/the_oddities.rpy", line 696, in script call
    call purchase_item(item_id,price4)
  File "game/00_hp_rpy/01_hp.rpy", line 807, in script call
    call c_r_night
  File "game/00_hp_rpy/17_books.rpy", line 299, in script call
    call reading_book_block(5)
  File "game/00_hp_rpy/17_books.rpy", line 651, in script call
    call check_book(bookID)
  File "game/00_hp_rpy/17_books.rpy", line 626, in script call
    call check_book(bookID)
  File "game/00_hp_rpy/17_books.rpy", line 626, in script call
    call check_book(bookID)
  File "game/00_hp_rpy/17_books.rpy", line 626, in script call
    call check_book(bookID)
  File "game/00_hp_rpy/17_books.rpy", line 626, in script call
    call check_book(bookID)
  File "game/00_hp_rpy/17_books.rpy", line 626, in script call
    call check_book(bookID)
  File "game/00_hp_rpy/17_books.rpy", line 626, in script call
    call check_book(bookID)
  File "game/00_hp_rpy/17_books.rpy", line 626, in script call
    call check_book(bookID)
  File "game/00_hp_rpy/17_books.rpy", line 626, in script call
    call check_book(bookID)
  File "game/00_hp_rpy/17_books.rpy", line 626, in script call
    call check_book(bookID)
  File "game/00_hp_rpy/17_books.rpy", line 622, in script call
    call chapter_check_book(bookID)
  File "game/00_hp_rpy/17_books.rpy", line 595, in script call
    call book_done_b_check_fire
  File "game/00_hp_rpy/17_books.rpy", line 324, in script call
    call reading_book_block(6)
  File "game/00_hp_rpy/17_books.rpy", line 651, in script call
    call check_book(bookID)
  File "game/00_hp_rpy/17_books.rpy", line 626, in script call
    call check_book(bookID)
  File "game/00_hp_rpy/17_books.rpy", line 626, in script call
    call check_book(bookID)
  File "game/00_hp_rpy/17_books.rpy", line 626, in script call
    call check_book(bookID)
  File "game/00_hp_rpy/17_books.rpy", line 626, in script call
    call check_book(bookID)
  File "game/00_hp_rpy/17_books.rpy", line 626, in script call
    call check_book(bookID)
  File "game/00_hp_rpy/17_books.rpy", line 626, in script call
    call check_book(bookID)
  File "game/00_hp_rpy/17_books.rpy", line 626, in script call
    call check_book(bookID)
  File "game/00_hp_rpy/17_books.rpy", line 626, in script call
    call check_book(bookID)
  File "game/00_hp_rpy/17_books.rpy", line 626, in script call
    call check_book(bookID)
  File "game/00_hp_rpy/17_books.rpy", line 622, in script call
    call chapter_check_book(bookID)
  File "game/00_hp_rpy/17_books.rpy", line 595, in script call
    call book_done_b_check_fire
  File "game/00_hp_rpy/01_hp.rpy", line 807, in script call
    call c_r_night
  File "game/00_hp_rpy/17_books.rpy", line 352, in script call
    call reading_book_block(7)
  File "game/00_hp_rpy/17_books.rpy", line 651, in script call
    call check_book(bookID)
  File "game/00_hp_rpy/17_books.rpy", line 626, in script call
    call check_book(bookID)
  File "game/00_hp_rpy/17_books.rpy", line 626, in script call
    call check_book(bookID)
  File "game/00_hp_rpy/17_books.rpy", line 626, in script call
    call check_book(bookID)
  File "game/00_hp_rpy/17_books.rpy", line 626, in script call
    call check_book(bookID)
  File "game/00_hp_rpy/17_books.rpy", line 626, in script call
    call check_book(bookID)
  File "game/00_hp_rpy/17_books.rpy", line 626, in script call
    call check_book(bookID)
  File "game/00_hp_rpy/17_books.rpy", line 626, in script call
    call check_book(bookID)
  File "game/00_hp_rpy/17_books.rpy", line 626, in script call
    call check_book(bookID)
  File "game/00_hp_rpy/17_books.rpy", line 626, in script call
    call check_book(bookID)
  File "game/00_hp_rpy/17_books.rpy", line 622, in script call
    call chapter_check_book(bookID)
  File "game/00_hp_rpy/17_books.rpy", line 595, in script call
    call book_done_b_check_fire
  File "game/00_hp_rpy/17_books.rpy", line 383, in script call
    call reading_book_block(8)
  File "game/00_hp_rpy/17_books.rpy", line 651, in script call
    call check_book(bookID)
  File "game/00_hp_rpy/17_books.rpy", line 626, in script call
    call check_book(bookID)
  File "game/00_hp_rpy/17_books.rpy", line 626, in script call
    call check_book(bookID)
  File "game/00_hp_rpy/17_books.rpy", line 626, in script call
    call check_book(bookID)
  File "game/00_hp_rpy/17_books.rpy", line 626, in script call
    call check_book(bookID)
  File "game/00_hp_rpy/17_books.rpy", line 626, in script call
    call check_book(bookID)
  File "game/00_hp_rpy/17_books.rpy", line 626, in script call
    call check_book(bookID)
  File "game/00_hp_rpy/17_books.rpy", line 626, in script call
    call check_book(bookID)
  File "game/00_hp_rpy/17_books.rpy", line 626, in script call
    call check_book(bookID)
  File "game/00_hp_rpy/17_books.rpy", line 626, in script call
    call check_book(bookID)
  File "game/00_hp_rpy/17_books.rpy", line 622, in script call
    call chapter_check_book(bookID)
  File "game/00_hp_rpy/17_books.rpy", line 595, in script call
    call book_done_b_check_fire
  File "game/00_hp_rpy/01_hp.rpy", line 807, in script call
    call c_r_night
  File "game/00_hp_rpy/01_hp.rpy", line 807, in script call
    call c_r_night
  File "game/00_hp_rpy/01_hp.rpy", line 807, in script call
    call c_r_night
  File "game/00_hp_rpy/17_books.rpy", line 438, in script call
    call reading_book_block(10)
  File "game/00_hp_rpy/17_books.rpy", line 651, in script call
    call check_book(bookID)
  File "game/00_hp_rpy/17_books.rpy", line 626, in script call
    call check_book(bookID)
  File "game/00_hp_rpy/17_books.rpy", line 626, in script call
    call check_book(bookID)
  File "game/00_hp_rpy/17_books.rpy", line 626, in script call
    call check_book(bookID)
  File "game/00_hp_rpy/17_books.rpy", line 626, in script call
    call check_book(bookID)
  File "game/00_hp_rpy/17_books.rpy", line 626, in script call
    call check_book(bookID)
  File "game/00_hp_rpy/17_books.rpy", line 626, in script call
    call check_book(bookID)
  File "game/00_hp_rpy/17_books.rpy", line 626, in script call
    call check_book(bookID)
  File "game/00_hp_rpy/17_books.rpy", line 626, in script call
    call check_book(bookID)
  File "game/00_hp_rpy/17_books.rpy", line 626, in script call
    call check_book(bookID)
  File "game/00_hp_rpy/17_books.rpy", line 626, in script call
    call check_book(bookID)
  File "game/00_hp_rpy/17_books.rpy", line 626, in script call
    call check_book(bookID)
  File "game/00_hp_rpy/17_books.rpy", line 626, in script call
    call check_book(bookID)
  File "game/00_hp_rpy/17_books.rpy", line 626, in script call
    call check_book(bookID)
  File "game/00_hp_rpy/17_books.rpy", line 626, in script call
    call check_book(bookID)
  File "game/00_hp_rpy/17_books.rpy", line 626, in script call
    call check_book(bookID)
  File "game/00_hp_rpy/17_books.rpy", line 626, in script call
    call check_book(bookID)
  File "game/00_hp_rpy/17_books.rpy", line 626, in script call
    call check_book(bookID)
  File "game/00_hp_rpy/17_books.rpy", line 626, in script call
    call check_book(bookID)
  File "game/00_hp_rpy/17_books.rpy", line 626, in script call
    call check_book(bookID)
  File "game/00_hp_rpy/17_books.rpy", line 622, in script call
    call chapter_check_book(bookID)
  File "game/00_hp_rpy/17_books.rpy", line 595, in script call
    call book_done_b_check_fire
  File "game/00_hp_rpy/01_hp.rpy", line 807, in script call
    call c_r_night
  File "game/00_hp_rpy/01_hp.rpy", line 807, in script call
    call c_r_night
  File "game/00_hp_rpy/01_hp.rpy", line 807, in script call
    call c_r_night
  File "game/00_hp_rpy/01_hp.rpy", line 807, in script call
    call c_r_night
  File "game/00_hp_rpy/01_hp.rpy", line 807, in script call
    call c_r_night
  File "game/00_hp_rpy/01_hp.rpy", line 807, in script call
    call c_r_night
  File "game/00_hp_rpy/09_summon_snape.rpy", line 43, in script call
    call not_today #Snape says: "I am busy tonight."
  File "game/00_hp_rpy/09_summon_snape.rpy", line 43, in script call
    call not_today #Snape says: "I am busy tonight."
  File "game/00_hp_rpy/01_hp.rpy", line 807, in script call
    call c_r_night
  File "game/00_hp_rpy/01_hp.rpy", line 807, in script call
    call c_r_night
  File "game/00_hp_rpy/01_hp.rpy", line 807, in script call
    call c_r_night
  File "game/00_hp_rpy/01_hp.rpy", line 807, in script call
    call c_r_night
  File "game/00_hp_rpy/01_hp.rpy", line 807, in script call
    call c_r_night
  File "game/00_hp_rpy/01_hp.rpy", line 807, in script call
    call c_r_night
  File "game/00_hp_rpy/01_hp.rpy", line 807, in script call
    call c_r_night
  File "game/00_hp_rpy/01_hp.rpy", line 807, in script call
    call c_r_night
  File "game/00_hp_rpy/01_hp.rpy", line 807, in script call
    call c_r_night
  File "game/00_hp_rpy/01_hp.rpy", line 807, in script call
    call c_r_night
  File "game/00_hp_rpy/01_hp.rpy", line 807, in script call
    call c_r_night
  File "game/00_hp_rpy/01_hp.rpy", line 807, in script call
    call c_r_night
  File "game/00_hp_rpy/01_hp.rpy", line 807, in script call
    call c_r_night
  File "game/00_hp_rpy/01_hp.rpy", line 807, in script call
    call c_r_night
  File "game/00_hp_rpy/01_hp.rpy", line 807, in script call
    call c_r_night
  File "game/00_hp_rpy/01_hp.rpy", line 807, in script call
    call c_r_night
  File "game/00_hp_rpy/01_hp.rpy", line 807, in script call
    call c_r_night
  File "game/00_hp_rpy/17_books.rpy", line 464, in script call
    call reading_book_block(11)
  File "game/00_hp_rpy/17_books.rpy", line 651, in script call
    call check_book(bookID)
  File "game/00_hp_rpy/17_books.rpy", line 626, in script call
    call check_book(bookID)
  File "game/00_hp_rpy/17_books.rpy", line 626, in script call
    call check_book(bookID)
  File "game/00_hp_rpy/17_books.rpy", line 626, in script call
    call check_book(bookID)
  File "game/00_hp_rpy/17_books.rpy", line 626, in script call
    call check_book(bookID)
  File "game/00_hp_rpy/17_books.rpy", line 626, in script call
    call check_book(bookID)
  File "game/00_hp_rpy/17_books.rpy", line 626, in script call
    call check_book(bookID)
  File "game/00_hp_rpy/17_books.rpy", line 626, in script call
    call check_book(bookID)
  File "game/00_hp_rpy/17_books.rpy", line 626, in script call
    call check_book(bookID)
  File "game/00_hp_rpy/17_books.rpy", line 626, in script call
    call check_book(bookID)
  File "game/00_hp_rpy/17_books.rpy", line 626, in script call
    call check_book(bookID)
  File "game/00_hp_rpy/17_books.rpy", line 626, in script call
    call check_book(bookID)
  File "game/00_hp_rpy/17_books.rpy", line 626, in script call
    call check_book(bookID)
  File "game/00_hp_rpy/17_books.rpy", line 626, in script call
    call check_book(bookID)
  File "game/00_hp_rpy/17_books.rpy", line 626, in script call
    call check_book(bookID)
  File "game/00_hp_rpy/17_books.rpy", line 626, in script call
    call check_book(bookID)
  File "game/00_hp_rpy/17_books.rpy", line 626, in script call
    call check_book(bookID)
  File "game/00_hp_rpy/17_books.rpy", line 626, in script call
    call check_book(bookID)
  File "game/00_hp_rpy/17_books.rpy", line 626, in script call
    call check_book(bookID)
  File "game/00_hp_rpy/17_books.rpy", line 626, in script call
    call check_book(bookID)
  File "game/00_hp_rpy/17_books.rpy", line 622, in script call
    call chapter_check_book(bookID)
  File "game/00_hp_rpy/17_books.rpy", line 595, in script call
    call book_done_b_check_fire
  File "game/00_hp_rpy/01_hp.rpy", line 807, in script call
    call c_r_night
  File "game/00_hp_rpy/34_clothes_store.rpy", line 143, in script call
    call clothes_store_gui
  File "game/00_hp_rpy/01_hp.rpy", line 807, in script call
    call c_r_night
  File "game/00_hp_rpy/23_personal_requests.rpy", line 3539, in script call
    call her_head("Well, I hope you enjoyed yourself, [genie_name]!","body_92")
  File "game/00_hp_rpy/33_mo.rpy", line 3053, in script
    her2 "[text]"
IOError: Couldn't find file '01_hp/08_animation_02/05_panties_01.png'.

**Comment by ta12345** [comment]
figured it out, line 3537 23_personal_requests.rpy should be 

```
$ h_c_u_pic = "01_hp/16_hermione_chibi/dance/05_panties_01.png"
```
